"""add_source_to_scans_and_reviews

Revision ID: bc18dce5c4e9
Revises: f513f21de8cb
Create Date: 2026-08-25 20:05:40.172958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc18dce5c4e9'
down_revision: Union[str, Sequence[str], None] = 'f513f21de8cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('scans', sa.Column('source', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'source')
    op.drop_column('reviews', 'source')
    # ### end Alembic commands ###
