"""Add 2FA fields

Revision ID: bcd4c96023fe
Revises: bc18dce5c4e9
Create Date: 2026-08-27 00:53:47.200981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcd4c96023fe'
down_revision: Union[str, Sequence[str], None] = 'bc18dce5c4e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('totp_secret', sa.String(length=32), nullable=True))
    op.add_column('businesses', sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'is_2fa_enabled')
    op.drop_column('businesses', 'totp_secret')
    # ### end Alembic commands ###
