"""add ai context fields

Revision ID: f513f21de8cb
Revises: e0abc9275a35
Create Date: 2026-08-23 00:50:56.099002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f513f21de8cb'
down_revision: Union[str, Sequence[str], None] = 'e0abc9275a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('custom_prompt', sa.Text(), nullable=True))
    op.add_column('businesses', sa.Column('scraped_context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'scraped_context')
    op.drop_column('businesses', 'custom_prompt')
    # ### end Alembic commands ###
